feat(rmp): common value handling for RMP helm

diff --git a/.github/workflows/helm-rmp.yaml b/.github/workflows/helm-rmp.yaml
--- a/.github/workflows/helm-rmp.yaml
+++ b/.github/workflows/helm-rmp.yaml
@@ -49,6 +49,7 @@ jobs:
           ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
           VALUES_FILE: values-full.yaml
         run: |
+          set +e
           RED="\033[1;31m"
           GREEN="\033[1;32m"
           YELLOW="\033[1;33m"
@@ -117,11 +118,10 @@ jobs:
             echo -e "${YELLOW}[ EXECUTING ] > Rendering for branch : ${GREEN}${suffix}${BLANK}"
             echo -e "${YELLOW}[ EXECUTING ] > Generating template for ${GREEN}${CHART_NAME}${YELLOW} version ${GREEN}${CHART_VERSION}${YELLOW} with values file ${GREEN}${path}/${VALUES_FILE}${YELLOW} to file ${GREEN}${suffix}/${CHART_NAME}_${path//\//_}_manifest_${suffix}.yaml${BLANK}"
 
-            common=$(find "$(dirname ${path})/values/" -maxdepth 1 -type f -name 'common-values.yaml' -print -quit)
-            if [ -f "${common}" ]
+            if [ -f "$(dirname ${path})/values/common-values.yaml" ]
             then
-              echo -e "${CYAN}[ INFO ] > Common values.yaml file found : ${PURPLE}${common}${BLANK}"
-              helm template "$CHART_NAME" "$path" -f "${common}" -f ${path}/${VALUES_FILE} > "${suffix}/${CHART_NAME}_${path//\//_}_manifest_${suffix}.yaml"
+              echo -e "${CYAN}[ INFO ] > Common values.yaml file found : ${PURPLE}$(dirname ${path})/values/common-values.yaml${BLANK}"
+              helm template "$CHART_NAME" "$path" -f "$(dirname ${path})/values/common-values.yaml" -f ${path}/${VALUES_FILE} > "${suffix}/${CHART_NAME}_${path//\//_}_manifest_${suffix}.yaml"
             else
               echo -e "${CYAN}[ INFO ] > No common values.yaml${BLANK}"
               helm template "$CHART_NAME" "$path" -f ${path}/${VALUES_FILE} > "${suffix}/${CHART_NAME}_${path//\//_}_manifest_${suffix}.yaml"
@@ -132,18 +132,36 @@ jobs:
               rm -rf "$suffix/oci_temp"
               echo -e "${CYAN}[ INFO ] > Cleaned up temporary OCI chart directory${BLANK}"
             fi
+            echo ""
           }
 
           for path in ${UNIQ_PATHS_CHANGED}
           do
             echo -e "${BLUE}[ STEP ] > Processing path ${YELLOW}${path}${BLANK}"
-
-            template_version "pr"
-
-            git checkout origin/main -- "$path"
-
-            template_version "main"
-            echo ""
+            if [ ! -f "${path}/Chart.yaml" ]
+            then
+              if [ -f "${path}/common-values.yaml" ]
+              then
+                echo -e "${CYAN}[ INFO ] > common-values.yaml has been modified, processing diff for all charts${BLANK}"
+                for dir in $(find "$(dirname ${path})" -mindepth 1 -maxdepth 1 -type d | grep -v '/values$')
+                do
+                  echo -e "${CYAN}[ INFO ] > Env ${PURPLE}$(basename ${dir})${BLANK}"
+                  old_path=${path}
+                  path=${dir}
+                  template_version "pr"
+                  git checkout origin/main -- "$(dirname ${old_path})"
+                  template_version "main"
+                  git checkout origin/${{ github.head_ref }} -- "$(dirname ${old_path})"
+                done
+              else
+                echo -e "${RED}[ ERROR ] > No helm chart found"
+                exit 1
+              fi
+            else
+              template_version "pr"
+              git checkout origin/main -- "$path"
+              template_version "main"
+            fi
           done
 
       - name: Generate dyff on release
